제목 : BERT 실습 - 마스크드 언어 모델 (Masked Language Model) 실습  
학습일 : 2022-07-11   
작성자 : [송유럽(Euro)](https://www.euroverse.dev/)  
관련 링크 : [딥러닝을 이용한 자연어처리 입문](https://wikidocs.net/153992)
  
--- 설명 ---  

--- 더 공부할 내용 ---  


In [2]:
from transformers import TFBertForMaskedLM
from transformers import AutoTokenizer

In [3]:
model = TFBertForMaskedLM.from_pretrained('bert-large-uncased')
tokenizer = AutoTokenizer.from_pretrained('bert-large-uncased')

All model checkpoint layers were used when initializing TFBertForMaskedLM.

All the layers of TFBertForMaskedLM were initialized from the model checkpoint at bert-large-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.
Downloading: 100%|██████████| 28.0/28.0 [00:00<00:00, 5.73kB/s]
Downloading: 100%|██████████| 226k/226k [00:00<00:00, 372kB/s] 
Downloading: 100%|██████████| 455k/455k [00:01<00:00, 457kB/s]  


In [6]:
inputs = tokenizer('Soccer is a really fun [MASK].', return_tensors='tf')
print(inputs['input_ids'])

tf.Tensor([[ 101 4715 2003 1037 2428 4569  103 1012  102]], shape=(1, 9), dtype=int32)


In [8]:
print(inputs['token_type_ids'])
print(inputs['attention_mask'])

tf.Tensor([[0 0 0 0 0 0 0 0 0]], shape=(1, 9), dtype=int32)
tf.Tensor([[1 1 1 1 1 1 1 1 1]], shape=(1, 9), dtype=int32)


In [9]:
from transformers import FillMaskPipeline
pip = FillMaskPipeline(model=model, tokenizer=tokenizer)
pip('Soccer is a really fun [MASK].')

[{'score': 0.7621118426322937,
  'token': 4368,
  'token_str': 'sport',
  'sequence': 'soccer is a really fun sport.'},
 {'score': 0.20341995358467102,
  'token': 2208,
  'token_str': 'game',
  'sequence': 'soccer is a really fun game.'},
 {'score': 0.012208560481667519,
  'token': 2518,
  'token_str': 'thing',
  'sequence': 'soccer is a really fun thing.'},
 {'score': 0.0018630244303494692,
  'token': 4023,
  'token_str': 'activity',
  'sequence': 'soccer is a really fun activity.'},
 {'score': 0.0013354836264625192,
  'token': 2492,
  'token_str': 'field',
  'sequence': 'soccer is a really fun field.'}]

In [10]:
pip('Euro is very [MASK] guy.')

[{'score': 0.34832027554512024,
  'token': 3835,
  'token_str': 'nice',
  'sequence': 'euro is very nice guy.'},
 {'score': 0.06406177580356598,
  'token': 2204,
  'token_str': 'good',
  'sequence': 'euro is very good guy.'},
 {'score': 0.04622715339064598,
  'token': 6047,
  'token_str': 'smart',
  'sequence': 'euro is very smart guy.'},
 {'score': 0.02771160565316677,
  'token': 4658,
  'token_str': 'cool',
  'sequence': 'euro is very cool guy.'},
 {'score': 0.01855863630771637,
  'token': 4086,
  'token_str': 'sweet',
  'sequence': 'euro is very sweet guy.'}]

위 결과를 보니 매우 정확한 모델인 듯 하다.